### ISSUE TITLE
Compiling on windows and ubuntu

### ISSUE THREAD

**Issue by hezishah** [urjaman/frser-duino#1]
Hi.

Thank you very much for this great project.

Could you write a short guide on how to compile.
I have tried several environments, all with similar issues:
1) Cygwin
2) Atmel Studio
3) Ubuntu 12.04

Thanks,
Hezi SHahmoon

**Comment by urjaman** [comment]
I'm not going to try and guess what exactly were your environments or what are "similar issues", pretty please logs next time. And even better would be pull requests with fixes.

The primary target compiling environment is recent (I have avr-gcc 4.9.2 in arch linux) avr toolchain on linux. 
I also have a "really old" target that i test on rarely with avr-gcc 4.6.3 (and associately old avr-libc),
and apparently that had a bug (just fixed that).

I also tested the Atmel Studio toolchain and it had a tiny issue that i fixed, so it seems to work - atleast the compilation, i dont have AVRs attached to the windows PC.
Does a warning about the uart ISR name but that seems to be spurious (checked with objdump).
Pointing cygwin at the AVR Toolchain inside Arduino 1.6.3 (mingw32 based) had the same issue as Atmel Studio, and behaves similarly... so now compiles.
I dont have a cygwin native avr toolchain at hand right now, so cant test that.

Note: You wont be able to clone the repository with only the Atmel Studio tools, so didnt test that (used cygwin git for that).

"Ubuntu 12.04" doesnt tell me much about what avr-toolchain they have :P, it is a linux distribution (one that i'd rather not touch if i dont have to...), thus I dont know what avr-gcc they ship. I might've fixed it if it was just an old avr toolchain...

short guide to compile, YMMV
    git clone --recursive https://github.com/urjaman/frser-duino.git
    cd frser-duino
    make

You might need to tune the Makefile if your avr toolchain is not in your path, or for the details of the avrdude command (when programming). I'm pretty sure the linux device names dont work on windows for example.

Btw, that "make" would try to make the u2 version, look at the README and the Makefile for ftdi version (really just different baudrate) and how it works, it really isnt that big of a file ;)
