### ISSUE TITLE
LTO

### ISSUE THREAD

**Issue by minzak** [urjaman/frser-duino#2]
Hi You maybe Missing LTO support and header files 

When i run make i got error:
cc1: error: LTO support has not been enabled in this configuration

Maybe this URL can little helps.
http://debian.2.n7.nabble.com/Bug-734055-gcc-arm-none-eabi-Missing-LTO-support-and-header-files-td3141874.html

**Comment by urjaman** [comment]
Thats not "my" (frser-duino's) problem, but a problem of your toolchain.
So build your avr-gcc with LTO enabled.

Workaround:
You can build it without LTO by taking -flto and -fwhole-program out of the makefile. The result will be bigger and maybe slower than what i meant, but it should still work.
