### ISSUE TITLE
Mega2560 requires upload.protocol stk500v2

### ISSUE THREAD

**Issue by zifxify** [urjaman/frser-duino#5]
(Mega 2560 R3)
avrdude -c arduino -p m2560 -P /dev/ttyACM0 -b 115200 -U flash:w:frser-duino.hex
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

should be avrdude -c stk500v2 -p m2560 -P /dev/ttyACM0 -b 115200 -U flash:w:frser-duino.hex

**Comment by urjaman** [comment]
That should do it.

EDIT: Oh and thanks for reporting (I dont have most of the hardware this thing supposedly supports, so i dont know if things are broken without these).
